- id: '1675621999349'
  alias: Auto-Light On
  description: ''
  trigger:
  - platform: event
    event_type: esphome.auto_light
    event_data:
      state: 'on'
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_pct: '{{states(''sensor.autolight_brightness'')}}'
      kelvin: '{{states(''sensor.autolight_kelvin'')}}'
      transition: '{{states(''input_number.autolight_transition_on'')}}'
    target:
      entity_id: '{{ trigger.event.data.entity_id }}'
  mode: single
  
- id: '1675622082283'
  alias: Auto-Light Off
  description: ''
  trigger:
  - platform: event
    event_type: esphome.auto_light
    event_data:
      state: 'off'
  condition: []
  action:
  - service: light.turn_off
    data:
      transition: '{{states(''input_number.autolight_transition_off'')}}'
    target:
      entity_id: '{{ trigger.event.data.entity_id }}'
  mode: single
